import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import fetcher from '../lib/fetcher'
import { ALL_POSTS } from '../lib/wordpress/api'
import styles from '../styles/Home.module.scss'

const Home = ({allPosts}) => {
  const [ showLogo, setShowLogo ] = useState(false)
  const posts = allPosts

  const LogoShow = () => {
    setShowLogo(true)
  }

  const LogoHide = () => {
    setShowLogo(false)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Karlo Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
        <div className={styles.textDiv}>
          <p>Juan Karlo Muro is a graphic designer and artist based in Fresno, California.</p>
          <p>He is the founder of <span className={styles.brand} onMouseEnter={LogoShow} onMouseLeave={LogoHide}>Studio Mala</span> a collaborative design studio.</p>
        </div>
        <div className={styles.textDiv}>
          <p>For freelance opportunities, collaborations, and availability</p>
          <p>please email <span className={styles.email}>info@juankarlomuro.com</span></p>
        </div>
      </div>
      <div className={showLogo ? styles.logo : styles.logoHide}>
        <img src="/static/images/logo.png" alt="Studio Mala Logo" />
      </div>
      {
        posts.map((post) => {
          return (
            <div className={styles.postContainer} key={post.id}>
              <div>
                {
                  post.featuredImage ?
                  <div className={styles.img}>
                      <img src={post.featuredImage.node.sourceUrl} alt={post.featuredImage.node.altText} />
                  </div>
                  :
                  null
                }
              </div>
            </div>
          )
        })
      }
    </div>
  )
}

export default Home

export async function getStaticProps() {
  const response = await fetcher(ALL_POSTS)
  const allPosts = response.data.posts.nodes

  return {
    props: {allPosts},
    revalidate: 1,
  }
}
